## R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown

after_success:
  - tar -C .. --xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - rm -rf CEdecisiontree.Rcheck
  - Rscript -e 'pkgdown::build_site()'
